'use strict';
// Generate accessible, printable fallback diagrams from the actual slide scenes.
// Run with --check to detect drift without writing files.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),c=vm.createContext({window:{}});
for(const file of ['slides/_shared/visuals.js','labs/_shared/teaching-traces.js','slides/_shared/trace-scenes.js','slides/decks/lectures-06-10.js','slides/decks/storage-choices.js','slides/decks/btree-growth.js','slides/decks/btree-clarity.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),c,{filename:file});
const {COURSE_DECKS:decks,DeckViz:V}=c.window;
const reading=path.join(root,'lectures/lecture-06'),html=fs.readFileSync(path.join(reading,'btrees.html'),'utf8');
const ids=[...html.matchAll(/data-btree-scene="([^"]+)"/g)].map(m=>m[1]);
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let changed=0;
for(const id of ids){
 const scene=decks[6].scenes.find(s=>s.id===id);if(!scene)throw new Error('Unknown reading scene: '+id);
 const svg=`<!-- Generated by scripts/build_btree_reading.cjs; edit the shared slide drawing. -->\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720" role="img" aria-labelledby="title desc" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif">\n<title id="title">${esc(scene.title)}</title><desc id="desc">${esc(scene.teaching.idea)}</desc>\n<rect width="1280" height="720" fill="#f7f6f2"/>\n`+V.sceneDrawing(scene,scene.steps-1).map(i=>`<${i.tag} ${Object.entries(i.attrs).map(([k,v])=>`${k}="${esc(v)}"`).join(' ')}>${i.text===undefined?'':esc(i.text)}</${i.tag}>`).join('\n')+'\n</svg>\n';
 const file=path.join(reading,'diagrams',id+'.svg');
 if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==svg){changed++;if(!process.argv.includes('--check')){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,svg);}else console.error('Stale reading diagram: '+id);}
}
console.log(`${ids.length} reading diagrams; ${changed} ${process.argv.includes('--check')?'out of date':'updated'}.`);
if(changed&&process.argv.includes('--check'))process.exitCode=1;
