#!/usr/bin/env python3
"""Embed exact Lab 5 Python source for the offline query walkthrough.

Run: python3 scripts/generate_lab5_query_source.py [--check]
Docstrings are omitted, but the displayed line numbers refer to the original file.
"""
import argparse
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'labs/lab-05/starter/sql_frontend.py'
OUTPUT = ROOT / 'labs/lab-05/query-trace-source.js'
METHODS = {
    'Lexer': ['__init__', 'peek', 'next', 'match', 'expect'],
    'Parser': ['parse', 'parse_query', '_parse_predicate', '_parse_term', '_parse_literal'],
    'Database': ['plan_query'],
}


def generate():
    source = SOURCE.read_text()
    lines = source.splitlines()
    methods = {}
    for cls in ast.parse(source).body:
        if not isinstance(cls, ast.ClassDef) or cls.name not in METHODS:
            continue
        for method in cls.body:
            if not isinstance(method, ast.FunctionDef) or method.name not in METHODS[cls.name]:
                continue
            omitted = set()
            if ast.get_docstring(method):
                doc = method.body[0]
                omitted.update(range(doc.lineno, doc.end_lineno + 1))
            methods[f'{cls.name}.{method.name}'] = [
                {'number': i, 'text': lines[i - 1][4:]}
                for i in range(method.lineno, method.end_lineno + 1)
                if i not in omitted
            ]
        if cls.name == 'Lexer':
            assignment = next(n for n in cls.body if isinstance(n, ast.Assign)
                              and any(isinstance(t, ast.Name) and t.id == 'TOKEN_RE' for t in n.targets))
            methods['Lexer.TOKEN_RE'] = [
                {'number': i, 'text': lines[i - 1][4:]}
                for i in range(assignment.lineno, assignment.end_lineno + 1)
            ]
    value = {'path': 'starter/sql_frontend.py', 'methods': methods}
    return ('/* Generated by scripts/generate_lab5_query_source.py. Do not edit. */\n'
            '(function(root) {\n  const source = ' + json.dumps(value, ensure_ascii=False, indent=2)
            + ';\n  if (typeof module === "object" && module.exports) module.exports = source;\n'
            '  else root.QueryTraceSource = source;\n})(typeof globalThis !== "undefined" ? globalThis : this);\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit('Query source is stale. Run python3 scripts/generate_lab5_query_source.py')
        print('Query walkthrough source matches the supplied Python methods.')
    else:
        OUTPUT.write_text(generated)
        print(OUTPUT.relative_to(ROOT))
