'use strict';
// Optional authoring tool: npm install playwright; then run with Node.
// Set PLAYWRIGHT_CHROMIUM_EXECUTABLE to use an existing Chromium installation.
// Measures all builds before course-clarity.js adds the common title and caption.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),context=vm.createContext({window:{},console});
for(const file of ['slides/_shared/visuals.js','labs/_shared/rag-measurements.js','labs/_shared/teaching-traces.js','slides/_shared/trace-scenes.js','slides/decks/lectures-01-05.js','slides/decks/lectures-06-10.js','slides/decks/lectures-11-15.js','slides/decks/teaching-notes.js','slides/decks/clarity-diagrams.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file});
const hidden=new Set(['cover','title','heading','title0','title1','title2']);
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});
 try{
  const page=await browser.newPage(),bounds={};
  const css=fs.readFileSync(path.join(root,'slides/_shared/deck.css'),'utf8');
  for(const deck of Object.values(context.window.COURSE_DECKS)){
   if(deck.id===6)continue;
   for(const scene of deck.scenes){
    const svgs=Array.from({length:scene.steps},(_,step)=>{
     const d=new context.window.DeckViz.Drawing();scene.draw(d,step);
     return '<svg viewBox="0 0 1280 720">'+d.items.filter(a=>a.tag!=='text'||!hidden.has(a.key)).map(a=>`<${a.tag} ${Object.entries(a.attrs).map(([k,v])=>`${k}="${esc(v)}"`).join(' ')}>${a.text===undefined?'':esc(a.text)}</${a.tag}>`).join('')+'</svg>';
    });
    await page.setContent('<style>'+css+'</style>'+svgs.join(''));
    bounds[deck.id+'/'+scene.id]=await page.locator('svg').evaluateAll(es=>{
     const b=es.map(e=>e.getBBox());
     return [Math.floor(Math.min(...b.map(r=>r.x)))-3,Math.floor(Math.min(...b.map(r=>r.y)))-3,Math.ceil(Math.max(...b.map(r=>r.x+r.width)))+3,Math.ceil(Math.max(...b.map(r=>r.y+r.height)))+3];
    });
   }
  }
  const result='/* Generated by scripts/measure_slide_layout.cjs from every unframed build.\n * Fixed bounds keep each diagram at one position and scale throughout its animation. */\nwindow.CourseClarityLayout = {\n'+Object.entries(bounds).map(([k,v])=>'  '+JSON.stringify(k)+': '+JSON.stringify(v)).join(',\n')+'\n};\n';
  fs.writeFileSync(path.join(root,'slides/decks/clarity-layout.js'),result);
  console.log('Measured '+Object.keys(bounds).length+' scene layouts.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
